### ISSUE TITLE
position and scope of namespace map

### ISSUE THREAD

**Issue by cKlee** [gbv/aREF#18]
@nichtich ,

from the spec I cannot falsify if this is possible:

``` yaml

---
http://example.com/people#alice:
    _ns:
        foaf: http://xmlns.com/foaf/0.1/
    a: foaf_Person
```

instead of:

``` yaml

---
_ns:
    foaf: http://xmlns.com/foaf/0.1/
http://example.com/people#alice:
    a: foaf_Person
```

If the first example is possible. What is the scope of the namespace map? In scope of the graph or in scope of the whole document?

``` yaml

---
http://example.com/people#alice:
    _ns:
        foaf: http://xmlns.com/foaf/0.1/
    a: foaf_Person
http://example.com/people#bob:
    a: foaf_Person
```
